
services:
    antemis:
        build:
            context: ..
            dockerfile: /Antemis/Dockerfile
        ports:
            - "8080:8080"
        container_name: Antemis
        depends_on:
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: genger404
        volumes:
            - db_data:/var/lib/postgresql/data
        container_name: f_postgres
volumes:
    db_data:
    